In [3]:
import numpy as np

In [67]:
def theta_1(P_x,P_y):
    return np.arctan2(P_y,P_x)

def theta_2(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4):
    R=np.sqrt(P_x**2+P_y**2)
    D_r=R-L_4*np.cos(beta)
    D_z=P_z-L_4*np.sin(beta)-L_1
    return -2*np.arctan((2*D_r*L_2 - np.sqrt(- D_r**4 - 2*D_r**2*D_z**2 + 2*D_r**2*L_2**2 + 2*D_r**2*L_3**2 - D_z**4 + 2*D_z**2*L_2**2 + 2*D_z**2*L_3**2 - L_2**4 + 2*L_2**2*L_3**2 - L_3**4))/(D_r**2 + D_z**2 + 2*D_z*L_2 + L_2**2 - L_3**2))

def theta_3(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4):
    R=np.sqrt(P_x**2+P_y**2)
    D_r=R-L_4*np.cos(beta)
    D_z=P_z-L_4*np.sin(beta)-L_1
    return -2*np.arctan((np.sqrt((- D_r**2 - D_z**2 + L_2**2 + 2*L_2*L_3 + L_3**2)*(D_r**2 + D_z**2 - L_2**2 + 2*L_2*L_3 - L_3**2)) - 2*L_2*L_3)/(D_r**2 + D_z**2 - L_2**2 - L_3**2))

def theta_4(beta,theta_2,theta_3):
    return beta-theta_2-theta_3

def ikine4r(P_x,P_y,P_z,beta):
    L_1=0.137
    L_2=0.105
    L_3=0.105
    L_4=0.095
    T1=theta_1(P_x,P_y)
    T2=theta_2(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4)
    T3=theta_3(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4)
    T4=theta_4(beta,T2,T3)
    return np.array([T1,T2,T3,T4])

def ConvGra2An(q,q_Home):
    ListDouble=q+q_Home
    for i in range(len(ListDouble)):
        ListDouble[i]=int(np.interp(ListDouble[i],[0, 300],[0, 1023]))
    return ListDouble


In [6]:
q_4=[95.84,92.92,48.34,222.36]
q_Home=[150,150,60,150]

np.multiply(np.subtract(q_4,q_Home),np.pi/180)

L_1=0.137
L_2=0.105
L_3=0.105
L_4=0.095

ikine4r(0.129,-0.179,0.1022,0,L_1,L_2,L_3,L_4)



array([-0.9463319 , -0.93998522, -0.23124155,  1.17122677])

In [68]:
q_4=np.array([0,0,0,0])
q_Home=np.array([150,150,60,150])

H=ConvGra2An(q_4,q_Home)


HomeS=np.array([0,0,0,0,0])
HomeC=np.array([0,0,0,0,70])
AngHome=np.array([150,150,60,150,150])
#Valores análogos de la posición home y los casos. Se obtuvieron desde dynamixel_wizard
PosAnHomeS=ConvGra2An(HomeS,AngHome)
PosAnHomeC=ConvGra2An(HomeC,AngHome)
print(PosAnHomeS)
print(PosAnHomeC)


Zpiso=0.095
Zportaherramientas=0.1


#Valores análogos de la posición home y los casos. Se obtuvieron desde dynamixel_wizard
PosAnHomeS=ConvGra2An(HomeS,AngHome)
PosAnHomeC=ConvGra2An(HomeC,AngHome)



AngPortaHerramientasArriba=ikine4r(0.1,-0.2,Zportaherramientas,0)
AngPortaHerramientasAbajo=ikine4r(0.1,-0.2,Zportaherramientas+0.05,0)


print(AngPortaHerramientasArriba)
print(AngPortaHerramientasAbajo)

[511 511 204 511 511]
[511 511 204 511 750]
[-1.10714872 -0.97106358 -0.18893574  1.15999931]
[-1.10714872 -0.56232242 -0.24466926  0.80699168]


In [73]:
lim=70*np.pi/180
AngArcMinIzq=ikine4r(0.168,0,Zpiso,0)
AngArcMinIzq[0]=lim
AngArcMinDer=ikine4r(0.168,0,Zpiso,0)
AngArcMinDer[0]=-lim

AngArcMaxIzq=ikine4r(0.3,0,Zpiso,0)
AngArcMaxIzq[0]=lim
AngArcMaxDer=ikine4r(0.3,0,Zpiso,0)
AngArcMaxDer[0]=-lim


print(AngArcMinIzq)
print(AngArcMinDer)
print(AngArcMaxIzq)
print(AngArcMaxDer)

[ 1.22173048 -0.93475153 -0.74547649  1.68022802]
[-1.22173048 -0.93475153 -0.74547649  1.68022802]
[ 1.22173048 -1.68880176  1.40264408  0.28615768]
[-1.22173048 -1.68880176  1.40264408  0.28615768]


In [123]:
Zpiso=0.095
Zportaherramientas=0.1
Zseguridad=0.15
beta=0

def ConvPosArr2QArr(PosArr):
    [r,c]=PosArr.shape
    QArr=np.zeros([r,c])
    for i in range(r):
        QArr[i,:]=ikine4r(PosArr[i,0],PosArr[i,1],PosArr[i,2],PosArr[i,3])    
    return QArr

PuntosA=np.array([[0.200,0.150,Zpiso,beta],[0.250,0.125,Zpiso,beta],[0.200,0.100,Zpiso,beta],[0.225,0.1125,Zpiso,beta],[0.225,0.1375,Zpiso,beta]])
PuntosJ=np.array([[0.250,0.100,Zpiso,beta],[0.250,0.050,Zpiso,beta],[0.250,0.075,Zpiso,beta],[0.200,0.075,Zpiso,beta],[0.200,0.100,Zpiso,beta]])
PuntosTri=np.array([[0.200,0,Zpiso,beta],[0.200,0.050,Zpiso,beta],[0.2433,0.025,Zpiso,beta],[0.200,0,Zpiso,beta]])
PuntosR1=np.array([[0.200,-0.050,Zpiso,beta],[0.200,-0.100,Zpiso,beta]])
PuntosR2=np.array([[0.225,-0.050,Zpiso,beta],[0.225,-0.100,Zpiso,beta]])
PuntosR3=np.array([[0.250,-0.050,Zpiso,beta],[0.250,-0.100,Zpiso,beta]])
PuntosEQTablero=np.array([[0.200,-0.125,Zpiso,beta],[0.210,-0.125,Zpiso,beta],[0.220,-0.125,Zpiso,beta],[0.230,-0.125,Zpiso,beta],[0.240,-0.125,Zpiso,beta],[0.250,-0.125,Zpiso,beta]])
PuntosEQSeguridad=np.array([[0.200,-0.125,Zseguridad,beta],[0.210,-0.125,Zseguridad,beta],[0.220,-0.125,Zseguridad,beta],[0.230,-0.125,Zseguridad,beta],[0.240,-0.125,Zseguridad,beta],[0.250,-0.125,Zseguridad,beta]])

#Qpuntos
QPuntosA=ConvPosArr2QArr(PuntosA)
QPuntosJ=ConvPosArr2QArr(PuntosJ)
QPuntosTri=ConvPosArr2QArr(PuntosTri)
QPuntosR1=ConvPosArr2QArr(PuntosR1)
QPuntosR2=ConvPosArr2QArr(PuntosR2)
QPuntosR3=ConvPosArr2QArr(PuntosR3)
QPuntosEQTablero=ConvPosArr2QArr(PuntosEQTablero)
QPuntosEQSeguridad=ConvPosArr2QArr(PuntosEQSeguridad)


In [128]:
AngHomeGrad=np.array([150,150,60,150,150])
AngHomeRad=np.multiply(AngHomeGrad,np.pi/180)
AngHomeRad



array([2.61799388, 2.61799388, 1.04719755, 2.61799388, 2.61799388])

In [11]:
from typing import Mapping

from numpy import interp
from numpy import pi
import numpy as np




def mapAn(theta):
    return int(interp(theta,[-150, 150],[0, 1023]))


mapAn(2)

902

In [ ]:
713
962
162